name: flutter_hrlweibo
description: A new Flutter application.
version: 1.0.0+1
homepage: https://github.com/huangruiLearn
funding: https://github.com/huangruiLearn/flutter_hrlweibo/blob/master/assets/images/shoukuan.png
platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  #https://github.com/luanpotter/audioplayers
  audioplayers: ^1.0.1
  #https://github.com/flutterchina/dio
  dio: ^4.0.6
  #https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  #https://github.com/best-flutter/flutter_page_indicator
  flutter_page_indicator: ^0.0.3
  #https://github.com/flutter/plugins/tree/master/packages/video_player
  video_player: ^2.4.7
  # https://github:com/brianegan/chewie
  chewie: ^1.3.4
  #https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  #https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # https://github:com/fluttercandies/extended_text_field:
  extended_text_field: ^10.1.1
  url_launcher: 5.3.0
  # https://github: com/fluttercandies/extended_nested_scroll_view:
  extended_nested_scroll_view: ^5.1.3
  #https://github.com/Daegalus/dart-uuid
  uuid: 3.0.1
  flutter_screenutil: ^0.5.2
  fluttertoast: ^3.1.0
  synchronized: ^2.1.0
  event_bus: ^1.0.1
  # https://github.com/theyakka/fluro
  fluro: ^2.0.3
  #https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.1+4
  #https://github.com/adee42/flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler:   '^3.0.0'
  #https://pub.flutter-io.cn/packages/audio_recorder
  flutter_record_plugin:
    git:
      url: https://github.com/huangruiLearn/flutter_record_plugin.git
      ref: 2c2d77bcbf284249fc1e43d965d3d416d5a7466f

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
   - family: HotSearch
     fonts:
      - asset: assets/fonts/Lobster-Regular.ttf

